[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Get your Infura API key at https://www.infura.io/networks/ethereum/linea
[rpc_endpoints]
linea-testnet = "https://linea-goerli.infura.io/v3/${INFURA_API_KEY}"
linea-mainnet = "https://linea-mainnet.infura.io/v3/${INFURA_API_KEY}"

# Request an API key at https://lineascan.build/
[etherscan]
linea-mainnet = { key = "${LINEA_EXPLORER_API_KEY}" }
linea-testnet = { key = "${LINEA_EXPLORER_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
